### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by kumuthak** [TasinIshmam/blockchain-academic-certificates#2]
When running "npm run start-development" in terminal, I get the following error:
> blockchain-certificate@1.0.0 start-development /Users/user/blockchain-academic-certificates/web-app
> cross-env NODE_ENV=development node -r dotenv/config ./bin/www

internal/fs/utils.js:626
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (/Users/user/blockchain-academic-certificates/web-app/services/fabric/enrollment.js:12:28)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/user/blockchain-academic-certificates/web-app/loaders/fabric-loader.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-certificate@1.0.0 start-development: `cross-env NODE_ENV=development node -r dotenv/config ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-certificate@1.0.0 start-development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-05-25T19_04_27_461Z-debug.log

**Comment by TasinIshmam** [comment]
Hi @kumuthak, 

Based on the stack trace I can see the error was on  [web-app/services/fabric/enrollment.js:12:28](https://github.com/TasinIshmam/blockchain-academic-certificates/blob/f7a66583312ecac2f8f2c4ce1f2b539ef5b72fc6/web-app/services/fabric/enrollment.js#L12).

The path argument passed to ```fs.readFileSync()```,  that is ```config.fabric.ccpPath``` variable is undefined. This variable is loaded into the ```config``` object from the ```.env``` file, which you must manually create (instructions can be found in the main readme of this project). 

This means either you did not set up the ```.env``` file properly or this file does not have a valid ```CCP_PATH``` entry. 

Hope this helps!

**Comment by kumuthak** [comment]
This is the sample.env file:

MONGODB_URI_LOCAL = mongodb://localhost:27017/blockchaincertificate
PORT = 3000
LOG_LEVEL = info
EXPRESS_SESSION_SECRET = sdfsdfddfgdfg3242efDFHI234 
CCP_PATH = /Users/user/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
FABRIC_CHANNEL_NAME = mychannel
FABRIC_CHAINCODE_NAME = fabcar_1

The CCP_PATH is correct but still I get the error.

**Comment by TasinIshmam** [comment]
That's strange. Could you print ```config.fabric.ccpPath``` on the console right before the faulting instruction and see if it returns the string or if it's undefined? 

If it's undefined, for one reason or another, the .env file isn't being read properly. Consider trying the following: 
1. Make sure you installled the dev-dependencies so that ```dot-env``` is properly installed. 
2. Make sure the environment file is called ```.env``` and not anything else.

**Comment by kumuthak** [comment]
Thanks! The issue was solved but the following error shows up:

> blockchain-certificate@1.0.0 start-development /Users/user/blockchain-academic-certificates/web-app
> cross-env NODE_ENV=development node -r dotenv/config ./bin/www

info: You are connected to the database
2021-05-26T14:24:11.053Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enroll endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054], stack=Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
    at ClientRequest.request.on (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19), errno=ECONNREFUSED, code=ECONNREFUSED, syscall=connect, address=127.0.0.1, port=7054
error: Failed to enroll admin user "admin": Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-certificate@1.0.0 start-development: `cross-env NODE_ENV=development node -r dotenv/config ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-certificate@1.0.0 start-development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-05-26T14_24_11_078Z-debug.log

**Comment by TasinIshmam** [comment]
This is because admin enrollment is failing. Refer to the ```enrollAdmin()``` function in ```web-app/services/fabric/enrollment.js``` where the error is emerging. 

The most likely reason for this is that the fabric server is simply not running. Did you make sure to follow all instructions necessary to package the chaincode and run the network in the [fabric documentation](https://hyperledger-fabric.readthedocs.io/en/release-2.2/deploy_chaincode.html)?

I know these errors are a bit frustrating. Fabric can be very difficult to set up and run :/

**Comment by kumuthak** [comment]
Thank you very much! The chain code package was not installed properly and now it is all fixed and running.

**Comment by TasinIshmam** [comment]
@kumuthak  

Glad I could help :)

**Comment by kumuthak** [comment]
Got this error when registering university and student:

fabric-ca request register failed with errors [[ { code: 20, message: 'Authentication failure' } ]]

Error: fabric-ca request register failed with errors [[ { code: 20, message: 'Authentication failure' } ]]
    at IncomingMessage.response.on (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:298:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by TasinIshmam** [comment]
Is the issue with both university and student? If enrollment is failing it's likely an issue on the Fabric side. 

Please make sure 

1. The fabric server is running and can enroll/create new users. (Consider testing by creating a user through the Fabric CLI tool to see if it works. You'll have to refer to the fabric documentation to learn how to do this.) 
2. Make sure mongoDB url is correct and you can connect to the database properly. 
3. There's a directory called "wallet" in the ```web-app``` directory and there are a set of keys for the admin user. This is necessary to enroll/register new users.  (Since you had no issue with admin enrollment, there should already be a key available here.) 

This is a guess, but the problem might be with the ```registerUser``` function in ```web-app/services/fabric/enrollment.js```. Perhaps you could try running a debugger to see what the faulting instruction is?

**Comment by kumuthak** [comment]
Yes, the issue is with both university and student. 
the database is connected successfully and there are a set of keys for the admin user. the fabric server is running but I don't know how to create a user through the Fabric CLI tool.

When I run the enrollment.js with debugger, I get this error:

internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.openSync (fs.js:435:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/Users/user/blockchain-academic-certificates/web-app/services/fabric/enrollment.js:12:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/user/blockchain-academic-certificates/web-app/loaders/fabric-loader.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-certificate@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-certificate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-05-29T14_39_00_469Z-debug.log

**Comment by TasinIshmam** [comment]
Hi @kumuthak, sorry for the delay. 

I think for whatever reason, the server is having issues loading config variables from the ```.env``` file. Take a look at ```web-app/loaders/config.js```, where all environment variables are loaded into the app. 

I would suggest simply hardcoding all the environment variables here directly as a temporary fix (the same ones you're curently placing on your ```.env``` file). For example, there's a key called ```fabric.cppPath``` where you should set your existing value for ```CCP_PATH``` stored in the ```.env``` file. 

If this solves the problem then it's clear the issue is with loading environment variables and not with the fabric network.

**Comment by kumuthak** [comment]
this is the config.js file after i made the changes:

//add configuration files
//initialize environment variables
//try to use the export from this file instead of touching process.env directly.


const env = process.env.NODE_ENV || 'development';

if (env === 'development') {
    process.env.MONGODB_URI = "mongodb://localhost:27017/test";  //in case of dev, connect to local URI.
    process.env.NODE_ENV = 'development';
}


module.exports = {
    mongodbURI: process.env.MONGODB_URI,
    port: 3000,
    logLevel: process.env.LOG_LEVEL || "info",
    expressSessionSecret: "sdfsdfddfgdfg3242efDFHI234",


    fabric: {
        ccpPath: "/Users/user/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json",
        walletPath: require('path').resolve(__dirname, "..", "wallet"),
        channelName : "mychannel",
        chaincodeName : "fabcar_1"
    }
};
 but still i get the same authentication failure error.

**Comment by kumuthak** [comment]
If I delete the wallet folder and try to run it, i get the following error when registering:

DiscoveryService: fabcar_1 error: failed constructing descriptor for chaincodes:<name:"fabcar_1" >

Error: DiscoveryService: fabcar_1 error: failed constructing descriptor for chaincodes:<name:"fabcar_1" > 
    at DiscoveryService.send (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-common/lib/DiscoveryService.js:333:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by TasinIshmam** [comment]
This seems definitely like an error from the fabric side. Unfortunately, I haven't been using Fabric for a while and can't help you much to debug :( 

To the best of my knowledge Fabric has a dedicated docker image to monitor network activity and output logs for debugging purposes. Perhaps that would be a promising place to look. If this is too difficult, I'd suggest trying out the [blockchain-vscode-extension ](https://github.com/IBM-Blockchain/blockchain-vscode-extension) from IBM that lets you run a blockchain network directly through your vscode GUI. It's a lot simpler to get started with compard to the scripts that the fabric documentation points towards.

**Comment by kumuthak** [comment]
Greetings of the Day!
Thank you very much for your response and suggestions.

**Comment by TasinIshmam** [comment]
Welcome and good luck!

**Comment by kumuthak** [comment]
Hi @TasinIshmam, I solved the fabric issues and when issuing the certificate I get the following error:

DiscoveryService: mychannel error: access denied

Error: DiscoveryService: mychannel error: access denied
    at DiscoveryService.send (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-common/lib/DiscoveryService.js:333:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NetworkImpl._initializeInternalChannel (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-network/lib/network.js:278:13)
    at async NetworkImpl._initialize (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-network/lib/network.js:230:9)
    at async Gateway.getNetwork (/Users/user/blockchain-academic-certificates/web-app/node_modules/fabric-network/lib/gateway.js:330:9)
    at async connectToNetwork (/Users/user/blockchain-academic-certificates/web-app/services/fabric/chaincode.js:35:22)
    at async Object.invokeChaincode (/Users/user/blockchain-academic-certificates/web-app/services/fabric/chaincode.js:55:26)
    at async generateMerkleTree (/Users/user/blockchain-academic-certificates/web-app/services/encryption.js:17:22)
    at async Object.generateMerkleRoot (/Users/user/blockchain-academic-certificates/web-app/services/encryption.js:41:18)
    at async Object.issueCertificate (/Users/user/blockchain-academic-certificates/web-app/services/university-service.js:25:22)
    at async postIssueCertificate (/Users/user/blockchain-academic-certificates/web-app/controllers/university-controller.js:73:31)

**Comment by kumuthak** [comment]
And when invoking chaincode, I get this error:

Error: endorsement failure during query. response: status:500 message:"error in simulation: failed to execute transaction d8f6cf813a4ad1e0c3447fb6cf5565e203c2bbed14af4582978ec239023e9617: could not launch chaincode fabcar:ace99692d028cbcfd02143eb93cae395379127e5dadc17482325b9f28739031d: error starting container: error starting container: API error (404): network _test not found"

**Comment by TasinIshmam** [comment]
Hey, like I said previously, it's very hard to debug issues on the Fabric network side without more information. Are you able to get logs in the fabric network? That should have more information on what the issue is. 

Additionally, are you able to invoke the chaincode manually (through the command line)?

**Comment by kumuthak** [comment]
hi, Thanks for your reply.
yes,I am able to invoke the chaincode manually now. 
 when issuing the certificate I get the following error:


Error: error in simulation: transaction returned with failure: Error: You've asked to invoke a function that does not exist: queryCertificateSchema
    at SingleQueryHandler.evaluate (/home/user/blockchain-academic-certificates/web-app/node_modules/fabric-network/lib/impl/query/singlequeryhandler.js:41:27)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Transaction.evaluate (/home/user/blockchain-academic-certificates/web-app/node_modules/fabric-network/lib/transaction.js:275:25)
    at async Object.invokeChaincode (/home/user/blockchain-academic-certificates/web-app/services/fabric/chaincode.js:65:32)
    at async generateMerkleTree (/home/user/blockchain-academic-certificates/web-app/services/encryption.js:17:22)
    at async Object.generateMerkleRoot (/home/user/blockchain-academic-certificates/web-app/services/encryption.js:41:18)
    at async Object.issueCertificate (/home/user/blockchain-academic-certificates/web-app/services/university-service.js:25:22)
    at async postIssueCertificate (/home/user/blockchain-academic-certificates/web-app/controllers/university-controller.js:73:31)

**Comment by TasinIshmam** [comment]
Did you package the chaincode *for this application* properly? It seems strange that the function straight up does not exist. 

Verify two things

1. Find the name of the chaincode when you import it over in fabric. See if it matches with the chaincode name on your application side. If I remember correctly, unless you change anything it will be *fabcar* or something similar. 
2. Invoke ```queryCertificateSchema``` manually through the command line inside your fabric network. If it still gives you the does not exist error, that's a clear indicator you didn't package the chaincode properly. (Perhaps you're accidentally packaging the default/demo fabcar chaincode instead).

**Comment by kumuthak** [comment]
Hi thank you very much.
I have packaged the default fabcar chaincode only, I don't know how to package the chaincode for this application. Can you help me with the steps?

**Comment by TasinIshmam** [comment]
This depends on your version of Hyperledger Fabric and your directory structure, so I can't give exact commands. I remember using version V2.1 for which the instructions can be found [here](https://hyperledger-fabric.readthedocs.io/en/release-2.1/deploy_chaincode.html#javascript). 

However, the process is largely the same across ```v2```. You will have to go to the ```chaincode``` directory and run the appropriate instructions. In the docs, the chaincode directory is ```fabric-samples/chaincode/fabcar/javascript```, so match appropriately. 

Additionally, when invoking the ```peer lifecycle chaincode package``` command, make sure that the argument to the ```--lang``` flag is ```node``` and the argument to the ```--label``` flag matches the ```FABRIC_CHAINCODE_NAME``` env variable. For the config example you showed me, it should be ``` fabcar_1```. 

Finally, if all of this is too confusing, the vs code extension I mentioned previously makes packaging chaincode quite a bit easier. I'm not sure how well maintained it is though.

**Comment by TasinIshmam** [comment]
Closing due to inactivity.
